name: Run UI Tests

on:
  repository_dispatch:
    types: [trigger-from-repo-source]

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Scoop and Allure CLI
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          iwr -useb get.scoop.sh | iex
          scoop install allure
          echo "$HOME\scoop\apps\allure\current\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
          
      - name: Run tests
        run: mvn clean test

      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
